### ISSUE TITLE
Misbehaves on Windows 7 due to incorrect permissions and missing error handling

### ISSUE THREAD

**Issue by nyanpasu64** [akiver/AltBacktick#11]
On Windows 7, AltBacktick switches between *all* windows regardless of source process. Normally you'd brush this off as "OS version is not supported", but interestingly I found that it crashes because `GetProcessNameFromProcessId` calls `OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION)` then `GetModuleFileNameEx` on the resulting handle. On Windows 7, this writes an empty string, returns 0 (error), and sets a GetLastError of "Access Denied (5)". However you don't check the error code, so proceed treating every PID as belonging to the same process "".

Interestingly, the [Microsoft docs on `GetModuleFileNameEx[W]`](https://learn.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getmodulefilenameexw) say that you need "PROCESS_QUERY_INFORMATION and PROCESS_VM_READ access rights". So your existing code may have actually been incorrect according to documentation. But apparently it still works on Windows 10 for some reason?

Replacing `PROCESS_QUERY_LIMITED_INFORMATION` with `PROCESS_QUERY_INFORMATION | PROCESS_VM_READ` makes this program work on Windows 7 again, and still functions on 10 (did not test on Windows 8/8.1 or 11). Is this change worth adding in mainline?

Interestingly, [`QueryFullProcessImageNameW`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-queryfullprocessimagenamew) *does* work with `PROCESS_QUERY_LIMITED_INFORMATION` according to documentation. Did you mean to use that function or not?

**Comment by akiver** [comment]
Hello,

I added the flag `PROCESS_VM_READ` in version 1.2.0, it should work on Windows 7 now.
I prefer to stick with `GetModuleFileNameEx` because the doc says `QueryFullProcessImageName` is available only on Vista or later.

Thank you for your investigation.
