### ISSUE TITLE
[Request] Pressing Alt+Backtick, letting go, then pressing them again should alternate between two windows

### ISSUE THREAD

**Issue by robmonte** [akiver/AltBacktick#2]
This is somewhere between a feature request and a recommendation. Pressing Alt+Backtick once, letting go, then pressing again, should simply alternate between two windows of the same application.

To compare to Alt+Tab:
When you press and hold Alt, then repeatedly press Tab, it goes through your application window list in order.
If you press and hold Alt, then press Tab once and let both go, it will switch to the next window only. Next, if you press and hold Alt, then press Tab once and let both go, it will instead go back to the previous window instead of the third window down the line.

Currently AltBacktick does not act in this way, but I think it would be a reasonable assumption for this to be the default behavior. Alternating between two windows is a pretty standard practice.

**Comment by akiver** [comment]
Added in v1.4.0, thanks @Quipyowert2!
