### ISSUE TITLE
[Request] Allow the user to customize the hotkey

### ISSUE THREAD

**Issue by robmonte** [akiver/AltBacktick#3]
I think it would be great if the program allowed adjustments to the hotkey, even if it is only minor choices. For example, I think choosing between Alt+Backtick or Ctrl+Backtick would be extremely helpful to some. Personally, I have hand issues and for that reason I remap Ctrl to my Alt key (so I can use copy/paste/etc). Because of that, I'd like to use Ctrl+Backtick instead for the shortcut (so physically it's like I'm pressing Alt anyway!)

I can understand if allowing _any_ key combination might be much more difficult to implement, so perhaps that's not as feasible of a request.

**Comment by kongxiangxin** [comment]
for the same reason, I had exchanged my ctrl and alt key... I think it is a very common behavior among mac users。
I want to use Ctrl+Backtick too.
