### ISSUE TITLE
Ignore minimised windows

### ISSUE THREAD

**Issue by Vitaly-S-Pavlenko** [akiver/AltBacktick#9]
It would be nice if there was a feature to ignore minimised windows from switching. The behaviour of whether or not to ignore minimised windows could be controlled by a tickbox in the settings menu.

**Comment by Master-sx** [comment]
I really like `AltBacktick`! I previously used `Easy Windows Switcher` but I found it could not switch windows if those windows had been minimized. I think `Easy Windows Switcher` is more suitable for you currently. Of course your proposal is really nice.

**Comment by Morphin3** [comment]
+1,in mac it works as @Vitaly-S-Pavlenko said,minimized windows were ignored,it would be nice to add a toggle option.
I tried Easy Windows Switch @HangX-Ma ,it works the same as AltBacktick，it could swtich windows had beem minimized too.

**Comment by Morphin3** [comment]
+1,in mac it works as @Vitaly-S-Pavlenko said,minimized windows were ignored,it would be nice to add a toggle option.
I tried Easy Windows Switch @HangX-Ma ,it does not work on my PC ,win11.

**Comment by akiver** [comment]
Added in 1.4.0 - it's disabled by default, you have to enable it (see the readme):

```ini
[behavior]
ignore_minimized_windows=true
```
